name: SonarQube analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonarqube:
    uses: clubcedille/cedille-workflows/.github/workflows/sonarqube-scan.yaml@master
    with:
      project-key: ets-blockchain
      project-name: ETS Blockchain
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
